export const APP_NAME = 'SaniPay';
export const API_PREFIX = 'api/v1';

export const CURRENCY = {
  CODE: 'NGN',
  SYMBOL: '₦',
  KOBO_PER_NAIRA: 100n,
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_TRANSACTION_PIN: 'INVALID_TRANSACTION_PIN',
  WALLET_LOCKED: 'WALLET_LOCKED',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
